"""Generate _rmtest.html — index.html with the reduced-motion branch forced on.

The reduced-motion hero can otherwise only be seen by turning the OS setting off
and on (Windows: Settings > Accessibility > Visual effects > Animation effects),
which is slow to do and easy to forget to undo. This writes a copy with
`heroStill` pinned to true so the still-frame layout can be served and measured
directly.

    python render/preview_reduced.py        # writes _rmtest.html
    python render/preview_reduced.py --rm   # deletes it again

_rmtest.html is listed in .gitignore and .vercelignore: it is a local artefact
and must never be committed or published. Serve it with the "Static File Server
(npx serve)" launch config and open /_rmtest.html.

Note that this forces only the JS flag. The one thing it cannot exercise is the
matchMedia read inside shmScrollTo, which is evaluated per click — stub
window.matchMedia at runtime to test that path.
"""

import io
import os
import sys

SRC = "index.html"
DST = "_rmtest.html"
FLAG = "var heroStill = window.matchMedia('(prefers-reduced-motion: reduce)').matches;"
FORCED = "var heroStill = true;  /* FORCED — generated by render/preview_reduced.py */"


def main():
    if "--rm" in sys.argv:
        if os.path.exists(DST):
            os.remove(DST)
            print("removed " + DST)
        else:
            print(DST + " not present")
        return

    src = io.open(SRC, encoding="utf-8").read()
    n = src.count(FLAG)
    if n != 1:
        print("ABORT: the heroStill declaration matched %d times (need 1). "
              "It was renamed or moved — update FLAG in this script." % n)
        sys.exit(1)

    io.open(DST, "w", encoding="utf-8", newline="").write(src.replace(FLAG, FORCED, 1))
    print("wrote %s (reduced-motion branch forced on)" % DST)


if __name__ == "__main__":
    main()
